name: Build docker image and push
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      tags:
        description: "comma separated tags (ex: latest,1.0.0)"
        required: true
        type: string
      env:
        description: base64 encoded .env content (cat .env | base64)
        required: false
        default: ""
        type: string
      platforms:
        type: string
        required: false
        default: "linux/amd64,linux/arm64"
    secrets:
      HUB_HOST:
        required: true
      HUB_USERNAME:
        required: true
        description: registry login username
      HUB_PASSWORD:
        required: true
        description: registry login password
jobs:
  setup:
    runs-on: self-hosted
    outputs:
      HUB_HOST: ${{ steps.setup.outputs.APP_NAME }}
      HUB_USERNAME: ${{ steps.setup.outputs.TAGS }}
      HUB_PASSWORD: ${{ steps.env_file.outputs.ENV_FILE }}
    steps:
      - name: Setup
        id: setup
        run: |
          echo "HUB_HOST=$(${{ secrets.HUB_HOST }} | base64 -d)" >> $GITHUB_OUTPUT
          echo "HUB_USERNAME=$(${{ secrets.HUB_USERNAME }} | base64 -d)" >> $GITHUB_OUTPUT
          echo "HUB_PASSWORD=$(${{ secrets.HUB_PASSWORD }} | base64 -d)" >> $GITHUB_OUTPUT
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy Env
        if: ${{ inputs.env != ''}}
        run: echo ${{ inputs.env }} | base64 -d > .env

      - name: Decode Base64
        id: decode
        run: |
          echo "HUB_HOST=$(${{ secrets.HUB_HOST }} | base64 -d)" >> $GITHUB_OUTPUT
          echo "HUB_USERNAME=$(${{ secrets.HUB_USERNAME }} | base64 -d)" >> $GITHUB_OUTPUT
          echo "HUB_PASSWORD=$(${{ secrets.HUB_PASSWORD }} | base64 -d)" >> $GITHUB_OUTPUT

      - name: Login
        uses: "docker/login-action@v3"
        with:
          username: ${{ steps.decode.HUB_USERNAME }}
          password: ${{ steps.decode.HUB_PASSWORD }}
          registry: ${{ steps.decode.HUB_HOST }}

      - name: Build and Push Image
        run: |
          npx zx <<'EOF'
          const tags = process.env.TAGS.split(',')
          $.quote = it => it
          let tagsArgs = tags
            .map(tag => `-t ${process.env.REGISTRY}/${process.env.APP_NAME}:${tag}`)
            .join(' ');
          console.log(`docker buildx build --platform ${process.env.PLATFORMS} --push ${tagsArgs} .`)
          await $`docker buildx build --platform ${process.env.PLATFORMS} --push ${tagsArgs} .`
          EOF
        env:
          PLATFORMS: ${{ inputs.platforms}}
          REGISTRY: ${{ steps.decode.HUB_HOST }}
          APP_NAME: ${{ inputs.app_name}}
          TAGS: ${{ inputs.tags}}
