name: Build docker image and push
on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      app_name:
        required: true
        type: string
      tags:
        description: "comma separated tags (ex: latest,1.0.0)"
        required: true
        type: string
      env:
        description: base64 encoded .env content (cat .env | base64)
        default: ""
        type: string
      namespace:
        type: string
        default: "default"
      platforms:
        type: string
        default: "linux/amd64,linux/arm64"
    secrets:
      username:
        required: false
        description: registry login username
      password:
        required: false
        description: registry login password
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Copy Env
        if: ${{ inputs.env != ''}}
        run: echo ${{ inputs.env }} > .env

      - name: Login
        if: ${{ secrets.username != '' && secrets.password != '' }}
        uses: "docker/login-action@v3"
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          registry: ${{ inputs.registry }}

      - name: Build and Push Image
        run: |
          npx zx <<'EOF'
          const tags = process.env.TAGS.split(',')
          let tagsArgs = tags
            .map(tag => `-t ${process.env.REGISTRY}/${process.env.APP_NAME}:${tag}`)
            .join(' ');
          
          await $`docker buildx build --platform ${process.env.PLATFORMS} --push ${tagsArgs} .`
          EOF
        env:
          PLATFORMS: ${{ inputs.platforms}}
          REGISTRY: ${{ inputs.registry}}
          APP_NAME: ${{ inputs.app_name}}
          TAGS: ${{ inputs.tags}}
